name: Build sing-box on Windows

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout sing-box repository
        uses: actions/checkout@v2
        with:
          repository: SagerNet/sing-box  # 指定要检出的仓库

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          # Install Windows dependencies using Chocolatey
          choco install mingw

      - name: Build sing-box
        run: |
          # Set Go environment variables
          $env:GOPATH="$env:USERPROFILE\go"
          $env:GOROOT="C:\Go"
          $env:PATH="$env:PATH;$env:GOROOT\bin;$env:GOPATH\bin"

          # Clone submodules (if any)
          git submodule update --init --recursive

          # Build sing-box (adjust the command as per your build script)
          go build -o sing-box.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sing-box-build
          path: .\sing-box.exe
