name: Test

on:
  workflow_dispatch:  # 允许手动触发工作流
  # schedule:
  #   每周一凌晨 3:00 执行
  #   - cron: 00 03 * * 1

jobs:
  Build_Openwrt:

    name: Test
    runs-on: ubuntu-24.04
    # https://github.com/actions/runner-images#available-images
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        # 使用说明https://github.com/actions/checkout
        with:
          # 指定分支 留空使用默认分支
          ref: ''

      - name: test various
        run: |
          pwd
          ls
          # 获取删除列表+添加列表
          content=$(cat openwrt/del_packages openwrt/add_packages | tr '\n' ' ')
          echo "PACKAGES=$content" >> $GITHUB_ENV
          # 打印PACKAGES
      - name: Verify package variable
        run: |
          echo "Combined package: $PACKAGES"
          echo "$PACKAGES"
